### ISSUE TITLE
【Some files are missing】

### ISSUE THREAD

**Issue by luoqianhao** [MarcBotet/hamlet#1]
When I try to run the training instruction code
`python run_experiments.py --exp 0 --wandb 1 ` , I get the following error:
“python3.8/site-packages/mmcv/utilsOSError: DACS: pretrained/mitb1_modular.pth is not a checkpoint file”

I'm guessing it's the lack of a weight file.
Can you provide A config.py and mitb1_modular.pth?

**Comment by MarcBotet** [comment]
Hi, thanks for pointing that out. 
I forgot to remove the config.py from the gitignore, it is already uploaded. 
You can find the mitb1_modular.pth in https://drive.google.com/drive/folders/1p3VoGrsQsI7wMCYeAb7nYEImW0oIrmMR, you can find the link in the readme.

**Comment by Cascol-SCUT** [comment]
HI, thanks for your great work. I wonder if the provided pretrained weights is trained with stochastic depth?

**Comment by stefanxinhong** [comment]
I only find  mitb1_uda.pth in [ https://drive.google.com/drive/folders/1p3VoGrsQsI7wMCYeAb7nYEImW0oIrmMR ](url) but mitb1_modular.pth is missing. Whether are 'student_pretrained' and 'pretrained_segmentator' in experiment.py the same, i.e, mitb1_uda.pth?
