### ISSUE TITLE
No such file or directory: 'random_modules/random_[0.25, 0.25, 0.25, 0.25].npy'

### ISSUE THREAD

**Issue by Hectoor** [MarcBotet/hamlet#2]
When exp is set to -1.

Error:
FileNotFoundError: DACS: ModularEncoderDecoder: [Errno 2] No such file or directory: 'random_modules/random_[0.25, 0.25, 0.25, 0.25].npy'

where is this file?

When exp is set to 0.

Error:
free variable 'seed' referenced before assignment in enclosing scope
free variable 'uda' referenced before assignment in enclosing scope

**Comment by MarcBotet** [comment]
The random_modules file can be found in the readme. I updated it to make it clear.

Thanks for pointing out the errors in exp 0. Now these variables are declared correctly

**Comment by Iriswwhy** [comment]
But now the random_modules files are : "online_random_xx.npy". Here is still [Errno 2] No such file or directory: 'random_modules/random_[0.25, 0.25, 0.25, 0.25].npy'

**Comment by MarcBotet** [comment]
As long as you are not using the random policy this doesn't matter. Thanks for pointing this out, I have changed the default to None since it should work as well. I can't test it anymore, so please get back to me if you see that for any reason this gives an error.
