### ISSUE TITLE
About 'student_pretrained' and 'pretrained_segmentator' in experiment.py

### ISSUE THREAD

**Issue by stefanxinhong** [MarcBotet/hamlet#3]
I only find  mitb1_uda.pth in [ https://drive.google.com/drive/folders/1p3VoGrsQsI7wMCYeAb7nYEImW0oIrmMR ](url) but mitb1_modular.pth is missing. Whether are 'student_pretrained' and 'pretrained_segmentator' in experiment.py the same, i.e, mitb1_uda.pth?

**Comment by MarcBotet** [comment]
Hi, thanks for pointing that out. Yes, please use the same one: mitb1_uda.pth. Since --exp 0 is causing more problems than expect it, please use --exp -1 to run the code
