### ISSUE TITLE
mmseg api/test.py progbar typo?

### ISSUE THREAD

**Issue by hhhyyeee** [MarcBotet/hamlet#4]
The current code which updates the progress bar on inference phase is like this (line 165):

```
for _ in range(len(results)):
    prog_bar.update()
return results
```

But I noticed that this code makes the progbar update process run eternally.
Shouldn't it be changed like this?

```
for _ in range(len(result)):
    prog_bar.update()
return results
```

Thanks.

**Comment by MarcBotet** [comment]
Thanks for pointing this out! I have changed to the same way is done in the original code.
