### ISSUE TITLE
init_segmentor() in image_demo.py has 6 arguments while there are only 3 arguments in the function definition

### ISSUE THREAD

**Issue by Iriswwhy** [MarcBotet/hamlet#5]
The code in ./demo/image_demo.py is :
model = init_segmentor(
        **cfg,
        args.checkpoint,
        device=args.device,
        classes=get_classes(args.palette),
        palette=get_palette(args.palette),
        revise_checkpoint=[(r'^module\.', ''), ('model.', '')])**
while the init_segmentor funciton definition in ./mmseg/apis/inference.py is :
def init_segmentor(**config, checkpoint=None, device="cuda:0"**):
   
    if isinstance(config, str):
        config = mmcv.Config.fromfile(config)
    elif not isinstance(config, mmcv.Config):
        raise TypeError(
            "config must be a filename or Config object, " "but got {}".format(type(config))
        )
    config.model.pretrained = None
    config.model.train_cfg = None
    model = build_segmentor(config.model, test_cfg=config.get("test_cfg"))
    if checkpoint is not None:
        checkpoint = load_checkpoint(model, checkpoint, map_location="cpu")
        model.CLASSES = checkpoint["meta"]["CLASSES"]
        model.PALETTE = checkpoint["meta"]["PALETTE"]
    model.cfg = config  # save the config in the model for convenience
    model.to(device)
    model.eval()
    return model
When running the image_demo.py, shows:
TypeError: init_segmentor() got an unexpected keyword argument 'classes'
The num of arguments is not matched.

**Comment by Iriswwhy** [comment]
Besides, the format of the config file which is needed to be input into the image_demo.py is not clear.

**Comment by MarcBotet** [comment]
Hi. Please do not use image_demo.py. This code comes from the base repo and is not supported by us. The only way to execute the code is the one explained in the readme. Note that we focus on Online Training and we do not provide an already adapted model, all the code is thought to be used in training.

**Comment by Iriswwhy** [comment]
> Hi. Please do not use image_demo.py. This code comes from the base repo and is not supported by us. The only way to execute the code is the one explained in the readme. Note that we focus on Online Training and we do not provide an already adapted model, all the code is thought to be used in training.

Thanks for your answers.
